var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                               o                ",
   "                             oo                                                 ",
   "                            xxxx                                                ",
   "                            x  x                                o           xx  ",
   "  xx                        x  x                                             x  ",
   "  x                         x  x  o                                          x  ",
   "  x            o            x  x                                           o x  ",
   "  x          xxxx           x  x  o                                          x  ",
   "  x  @ yyyyy x  x         _ x  x       yyy   _              _   xxxxx        x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxx  xxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxx   xxxxxxxxxx  ",
   "                                             x!!!!!x                            ",
   "                                             x!!!!!x                            ",
   "                                             x!!!!!x                            ",
   "                                             xxxxxxx                            ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                                                                        ",
   "                                      x!!x                                                                        ",
   "                                      x!!xxxxxxxxxx                                                               ",
   "                                      xx!!!!!!!!!!xx                                                              ",
   "                                       xxxxxxxxxx!!x                                                              ",
   "                                                xx!x                                                              ",
   "                                                 x!x                                             o                ",
   "                                                 xvx                                   xxxxxxxxxxxxxxxxxx         ",
   "                                     xxxxxxxxxxx                                                                  ",
   "                                    x           x                                                                 ",
   "                                    x         x x                                                                 ",
   "                                    x           x                        x                                        ",
   "                                    x x       x x                        x                                        ",
   "                                    x x       x x        =   o           x                                        ",
   "                                    x xxxxxxxxx x    xxxxxxxxxxxxxxxxx   x                                        ",
   "                                    x x       x x    x               x   x           _                            ",
   "                                    x x       x x    x               x   x                                        ",
   "                                    x           x    x               x   x                                        ",
   "                                    x xxxxxxxxx x   xx               x   x                                        ",
   "     @                  xxxxxxxxx   x     x     x    x               x   x                                        ",
   "    xxx              xxx        x   x     x     x    x               x   xxxxx                                    ",
   "    x x       _   xxx          xx o x xxxxxxxxx x    x               x     o                                      ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!xx    x           x    x!!!!!!!!!!     x          y_                                ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx      xxxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!x    o                  x!!!!!!xx !                     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!x                   _   x!!!!!xx  !                     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx       xxxxxxxxxxxxxxxx!!!!xx   !                     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                             x                                                                          x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                         xxxxx         xxxxxxxxxxxx                                     x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x      @                    _            _            _                                                  x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   !!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxx  ",
   "                                                                      x * x                                    ",
   "                                                                      xxxxx                                   "],
  ["                                                                  ",
   "                                                                  ",
   "          x   x  xxx   x   x     x     x xxx  x    x  x           ",
   "           x x  x   x  x   x     x  x  x  x   xx   x  x           ",
   "           x x  x   x  x   x     x  x  x  x   x x  x  x           ",
   "            x   x   x  x   x     x  x  x  x   x  x x  x           ",
   "            x   x   x  x   x     x  x  x  x   x   xx              ",
   "            x    xxx    xxx       xx xx  xxx  x    x  o           ",
   "x        ===                                          ===        x",
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "          @                                                       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
